# Generated by Django 4.0.6 on 2023-01-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_deck_description_alter_deck_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='TimeToReview',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
