# Generated by Django 4.1.4 on 2023-01-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_holder_timetoreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='NeedToReview',
            field=models.BooleanField(default=False),
        ),
    ]
